#
# Makefile for the Synaptics DSX touchscreen driver.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_GT1X_ZTE) += gt1x.o
obj-$(CONFIG_TOUCHSCREEN_GT1X_ZTE) += gt1x_extents.o
obj-$(CONFIG_TOUCHSCREEN_GT1X_ZTE) += gt1x_generic.o
obj-$(CONFIG_TOUCHSCREEN_GT1X_ZTE) += gt1x_tools.o
obj-$(CONFIG_TOUCHSCREEN_GT1X_ZTE) += gt1x_update.o
obj-$(CONFIG_ZTE_TPD_SYS) += gt1x_test.o
obj-$(CONFIG_ZTE_TPD_SYS) += test_function.o
