/*
** Copyright (c) 2009-2015 by Silicon Laboratories
**
** $Id: si_voice_version.c 5181 2015-10-15 14:54:03Z nizajerk $
**
** si_voice_version.c
** ProSLIC API Version
**
** Author(s):
** cdp
**
** Distributed by:
** Silicon Laboratories, Inc
**
** This file contains proprietary information.
** No dissemination allowed without prior written permission from
** Silicon Laboratories, Inc.
**
** THIS FILE IS AUTOGENERATED - DO NOT MODIFY
**
*/

char *SiVoiceAPIVersion = "7.6.0";
